# Tulemused

## Õpiväljundid

Õpilane

1. arvutab peast (liitmine ja lahutamine 1000 piires, korrutamine ja jagamine 100 piires) ja kirjalikult (liitmine ja lahutamine 10 000 piires, korrutamine ja jagamine 1000 piires) täisarvude ning positiivsete ratsionaalarvudega (sealhulgas harilike murdudega, mille nimetajate vähim ühiskordne on kuni 100).

2. rakendab tehete järjekorda.

3. esitab liitfunktsiooni lihtsamate funktsioonide kaudu.

4. liidab ja lahutab peast arve 100 piires, kirjalikult 10 000 piires.

5. selgitab protsendi, promilli ja protsendipunkti mõiste tähendust.

6. lahendab lihtsamaid eksponent- ja logaritmvõrrandeid astme ning logaritmi definitsiooni ja logaritmi omaduste vahetu rakendamise teel.

7. kasutab (igapäevaelu) ülesannete lahendamisel otstarbekat osamäära esitusviisi (protsent, harilik murd, kümnendmurd).

8. lahendab ühe tundmatuga lineaar-, ruut-, murd- ja lihtsamaid juurvõrrandeid (kuni kaks juurt)
ning nendeks taanduvaid võrrandeid.

9.

10.

11.

12. kasutab protsentarvutust otsuse tegemiseks ja põhjendamiseks (nt laen, hoius, intress, maksud, investeerimine).

13.

14.

15.

16.

17. põhjendab ja kasutab astendamisreegleid.

18. liidab, lahutab, korrutab, jagab ja astendab naturaalarvulise astendajaga ratsionaalarve peast,
kirjalikult ja taskuarvutiga ning rakendab tehete järjekorda.

19.

20. korrastab üks- ja hulkliikmeid, liidab, lahutab ning korrutab üks- ja hulkliikmeid ning jagab
üksliikmeid ja hulkliiget üksliikmega.

21. üldistab harilike murdude arvutusreeglid algebralistele murdudele.

22. lihtsustab kahetehtelisi ratsionaalavaldisi.

23.

24. taandab ja laiendab algebralist murdu ning liidab, lahutab, korrutab ja jagab kaht algebralist
murdu.

25. teab põik- ja lähisnurkade mõisteid ja nende nurkade seoseid paralleelsete sirgete korral.

26.

27.

28.

29.

30.

31.

32.

33.

34. nimetab võrrandi põhiomadusi.

35.

36.

37. lahendab lineaar- ja võrdekujulisi võrrandeid ning lineaarvõrrandisüsteeme kasutades
võrrandi põhiomadusi (sh graafiliselt ning arvutiprogrammide abil).

38. lahendab täielikke ja mittetäielikke ruutvõrrandeid.

39.

40.

41. joonestab etteantud funktsiooni graafiku (sirge, hüperbooli, parabooli) (nii käsitsi kui ka arvutiprogrammiga) ning loeb graafikult funktsiooni ja argumendi väärtusi.

## Saavutatused

Õpilaste saavutatused on esitatud tabelis \@ref(tab:achievements).

<!-- \begin{landscape} -->

```{r label="achievements", echo=FALSE}
targets <- 1:41

names <- c(
	"Daniil Bondar", # 
	"Oleksandr Bosiuk", # 
	"Alger Bronzov", # 
	"Tikhon Cherkay", # 
	"Daniil Doronin", #
	"Ksenija Frolova", # 
	"Sofja Gubatšjova", # 
	"Jelena Ivleva",
	"Arno Kaseniit",
	"Oxana Klein", # 
	"Hlib Klyha", # 
	"Maksym Kotkov", # 
	"Ene Kruzman",
	"Maria Laanemäe",
	"Jan-Eerik Laende", # 
	"Anna Levchenko",
	"Olesja Makarova", # 
	"Egor Mikhaylov", # 
	"Sergey Mikheev", # 
	"Ruslana Nekrakha",
	"Irina Nitsenko", # 
	"Nikita Norman", # 
	"Angelina Pajuni",
	"Ivan Puzanov",
	"Uuno Puus",
	"Azhar Ryskhan", # 
	"Andrii Shnayder",
	"Vladislav Smirnov",
	"Mihhail Startsev", # 
	"Semjon Suhhotin", # 
	"Arina Šiškova", # 
	"Anton Zakharchenko", # 
	"Ivanna Zimina", # 
	"Marie Tombu", # 
	"Max Välja"
)

grades <- data.frame(
  c( # 1
  	1, # Daniil Bondar
  	1, # Oleksandr Bosiuk
  	1, # Alger Bronzov
  	1, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	1, # Ksenija Frolova
  	1, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	1, # Oxana Klein
  	1, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	1, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	1, # Olesja Makarova
  	1, # Egor Mikhaylov
  	1, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	1, # Irina Nitsenko
  	1, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	1, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	1, # Vladislav Smirnov
  	1, # Mihhail Startsev
  	1, # Semjon Suhhotin
  	1, # Arina Šiškova
  	1, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	1, # Marie Tombu
  	1 # Max Välja
  ),
  c( # 2
  	1, # Daniil Bondar
  	1, # Oleksandr Bosiuk
  	1, # Alger Bronzov
  	1, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	1, # Ksenija Frolova
  	1, # Sofja Gubatšjova
  	1, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	1, # Oxana Klein
  	NA, # Hlib Klyha
  	1, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	1, # Anna Levchenko
  	NA, # Olesja Makarova
  	1, # Egor Mikhaylov
  	1, # MikhSergey Mikheev
  	1, # Ruslana Nekrakha
  	1, # Irina Nitsenko
  	1, # Nikita Norman
  	1, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	1, # Azhar Ryskhan
  	1, # Andrii Shnayder
  	1, # Vladislav Smirnov
  	1, # Mihhail Startsev
  	1, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	1, # Marie Tombu
  	1 # Max Välja
  ),
  c( # 3
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	1, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	1, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 4
  	1, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	1, # Alger Bronzov
  	1, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	1, # Oxana Klein
  	1, # Hlib Klyha
  	1, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	1, # Anna Levchenko
  	1, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	1, # Sergey Mikheev
  	1, # Ruslana Nekrakha
  	1, # Irina Nitsenko
  	1, # Nikita Norman
  	NA, # Angelina Pajuni
  	1, # Ivan Puzanov
  	NA, # Uuno Puus
  	1, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	1, # Vladislav Smirnov
  	1, # Mihhail Startsev
  	1, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	1, # Anton Zakharchenko
  	1, # Ivanna Zimina
  	1, # Marie Tombu
  	1 # Max Välja
  ),
  c( # 5
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 6
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # Sergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 7
  	1, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	1, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	1, # Ksenija Frolova
  	1, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # Sergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	1, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	1, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	1, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	1, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	1, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 8
  	NA, # Daniil Bondar
  	1, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	1, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	1, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	1, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 9
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 10
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 11
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 12
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 13
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 14
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 15
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 16
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 17
  	1, # Daniil Bondar
  	1, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	1, # Ksenija Frolova
  	1, # Sofja Gubatšjova
  	1, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	1, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	1, # Anna Levchenko
  	1, # Olesja Makarova
  	1, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	1, # Irina Nitsenko
  	1, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	1, # Marie Tombu
  	1 # Max Välja
  ),
  c( # 18
  	1, # Daniil Bondar
  	1, # Oleksandr Bosiuk
  	1, # Alger Bronzov
  	1, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	1, # Ksenija Frolova
  	1, # Sofja Gubatšjova
  	1, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	1, # Oxana Klein
  	1, # Hlib Klyha
  	1, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	1, # Jan-Eerik Laende
  	1, # Anna Levchenko
  	NA, # Olesja Makarova
  	1, # Egor Mikhaylov
  	1, # MikhSergey Mikheev
  	1, # Ruslana Nekrakha
  	1, # Irina Nitsenko
  	1, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	1, # Azhar Ryskhan
  	1, # Andrii Shnayder
  	1, # Vladislav Smirnov
  	1, # Mihhail Startsev
  	1, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	1, # Marie Tombu
  	1 # Max Välja
  ),
  c( # 19
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 20
  	1, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	1, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	1, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	1, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	1, # Egor Mikhaylov
  	1, # Sergey Mikheev
  	NA, # Ruslana Nekrakha
  	1, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	1, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 21
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 22
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 23
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 24
  	1, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	1, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	1, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	1, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 25
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 26
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 27
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 28
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 29
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 30
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 31
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 32
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 33
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 34
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 35
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 36
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 37
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # Sergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 38
  	NA, # Daniil Bondar
  	1, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	1, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 39
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 40
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	NA, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	NA, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	NA, # Anna Levchenko
  	NA, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	NA, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	NA, # Marie Tombu
  	NA # Max Välja
  ),
  c( # 41
  	NA, # Daniil Bondar
  	NA, # Oleksandr Bosiuk
  	1, # Alger Bronzov
  	NA, # Tikhon Cherkay
  	NA, # Daniil Doronin
  	1, # Ksenija Frolova
  	NA, # Sofja Gubatšjova
  	NA, # Jelena Ivleva
  	NA, # Arno Kaseniit
  	NA, # Oxana Klein
  	NA, # Hlib Klyha
  	NA, # Maksym Kotkov
  	NA, # Ene Kruzman
  	NA, # Maria Laanemäe
  	NA, # Jan-Eerik Laende
  	1, # Anna Levchenko
  	1, # Olesja Makarova
  	NA, # Egor Mikhaylov
  	NA, # MikhSergey Mikheev
  	NA, # Ruslana Nekrakha
  	NA, # Irina Nitsenko
  	NA, # Nikita Norman
  	NA, # Angelina Pajuni
  	NA, # Ivan Puzanov
  	NA, # Uuno Puus
  	NA, # Azhar Ryskhan
  	NA, # Andrii Shnayder
  	1, # Vladislav Smirnov
  	NA, # Mihhail Startsev
  	NA, # Semjon Suhhotin
  	NA, # Arina Šiškova
  	NA, # Anton Zakharchenko
  	NA, # Ivanna Zimina
  	1, # Marie Tombu
  	NA # Max Välja
  )
)

data_frame <- grades[1]
for (target_identifier in 3:4) {
  data_frame <- cbind(data_frame, grades[target_identifier])
}
for (target_identifier in 6:8) {
  data_frame <- cbind(data_frame, grades[target_identifier])
}
data_frame <- cbind(data_frame, grades[17])
data_frame <- cbind(data_frame, grades[18])
data_frame <- cbind(data_frame, grades[20])
data_frame <- cbind(data_frame, grades[24])
data_frame <- cbind(data_frame, grades[37])
data_frame <- cbind(data_frame, grades[38])
data_frame <- cbind(data_frame, grades[41])

colnames(data_frame) <- c(targets[1], targets[3:4], targets[6:8], targets[17], targets[18], targets[20], targets[24], targets[37], targets[38], targets[41])

rownames(data_frame) <- names
table <- print_table(
  table = data_frame,
  caption = "Õpilaste saavutatud õpiväljundid."
) %>% landscape()

table

```

<!-- \end{landscape} -->
